import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './Navbar'
import { Theme, ThemePanel } from '@radix-ui/themes';
const inter = Inter({ subsets: ['latin'] })
import '@radix-ui/themes/styles.css';



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>

        <Navbar/>
        <main className='p-5 border-blue-300'>{children}</main>
        <ThemePanel/>
        </Theme>
        </body>
    </html>
  )
}
