import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './Navbar'
import { Container, Theme, ThemePanel } from '@radix-ui/themes';
const inter = Inter({ subsets: ['latin'] })
import '@radix-ui/themes/styles.css';
import AuthProvider from './auth/Provider';



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>

        <Theme appearance='light' accentColor='violet'>


        <Navbar/>
        <main className='p-5 border-blue-300'>
          <Container>

          {children}
          </Container>
          </main>

        </Theme>
        </AuthProvider>
        </body>
    </html>
  )
}
